# Generated by Django 3.2.15 on 2022-09-11 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='desc1',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='img1',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='name1',
            new_name='name',
        ),
    ]
