# Generated by Django 3.2.15 on 2022-09-11 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_auto_20220912_0332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='desc',
            new_name='desc1',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='img',
            new_name='img1',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='name1',
        ),
    ]
