# Generated by Django 3.2.15 on 2022-09-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_auto_20220912_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='img1',
            field=models.ImageField(upload_to='pics1'),
        ),
    ]
